kind: Secret
apiVersion: v1
metadata:
  namespace: demo
  name: example-secret
  annotations:
    avp_path: "heimdal-poc/data/demo/secret"
type: Opaque
stringData:
  username: <username>
  password: <password>
